[platformio]
src_dir = src

[env:cc1101]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = partitions_large_nvs.csv

lib_deps =
  knolleary/PubSubClient@^2.8
  bblanchon/ArduinoJson@^7.0.0

[env:cc1101_ota]
extends = env:cc1101
upload_protocol = espota
